name: Docker Hub Deployment  # Workflow for deploying Docker image to Docker Hub

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use an Ubuntu latest runner for the job

    steps:
      - name: Checkout code  # Step to checkout the code repository
        uses: actions/checkout@v2

      - name: Build Docker image  # Step to build Docker image
        run: |
          docker build \
            --file Dockerfile \
            --tag ${{ secrets.DOCKER_HUB_USERNAME }}/lifetracker:build-v1.064 \
            .
        continue-on-error: false  # Stop the workflow if building the Docker image fails
        timeout-minutes: 10  # Set a timeout for the build process

      - name: Login to Docker Hub  # Step to log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}  # Use Docker Hub username from secrets
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}  # Use Docker Hub access token from secrets
        continue-on-error: false  # Stop the workflow if login fails

      - name: Push Docker image  # Step to push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/lifetracker:build-v1.064
        continue-on-error: false  # Stop the workflow if pushing the Docker image fails
